[package]
name = "lnmarkets_data"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/lnmarkets_data.rs"

[dependencies]
anyhow.workspace = true
async-io.workspace = true
chrono.workspace = true
lnmarkets_client.workspace = true
log.workspace = true
parking_lot.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
futures.workspace = true
http.workspace = true
tempfile.workspace = true
