[package]
name = "lnmarkets_trading"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/lnmarkets_trading.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
lnmarkets_client.workspace = true
lnmarkets_data.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strategy_engine.workspace = true
trading_ledger.workspace = true
trading_mandate.workspace = true

[dev-dependencies]
futures.workspace = true
http.workspace = true
